// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz4eg1YLa-juqMrbim4B8jBIK13Ircack',
    appId: '1:212050889502:web:83276cb335d611a2ce570f',
    messagingSenderId: '212050889502',
    projectId: 'shop-local-b69a3',
    authDomain: 'shop-local-b69a3.firebaseapp.com',
    storageBucket: 'shop-local-b69a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV_Tm8KoVlY1xolCHBKbCXVEHBTYEGS5U',
    appId: '1:212050889502:android:8dc35fc3bd4d0ef3ce570f',
    messagingSenderId: '212050889502',
    projectId: 'shop-local-b69a3',
    storageBucket: 'shop-local-b69a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6O2lxv8Uy_o0k-_ZvqL4LTB0MCveiNM',
    appId: '1:212050889502:ios:860e0cf5519f0bd1ce570f',
    messagingSenderId: '212050889502',
    projectId: 'shop-local-b69a3',
    storageBucket: 'shop-local-b69a3.firebasestorage.app',
    iosClientId: '212050889502-qpv3pf411veqfp2ni6g17raiiaktfdt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6O2lxv8Uy_o0k-_ZvqL4LTB0MCveiNM',
    appId: '1:212050889502:ios:860e0cf5519f0bd1ce570f',
    messagingSenderId: '212050889502',
    projectId: 'shop-local-b69a3',
    storageBucket: 'shop-local-b69a3.firebasestorage.app',
    iosClientId: '212050889502-qpv3pf411veqfp2ni6g17raiiaktfdt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz4eg1YLa-juqMrbim4B8jBIK13Ircack',
    appId: '1:212050889502:web:2f5cd8c07f9e75c3ce570f',
    messagingSenderId: '212050889502',
    projectId: 'shop-local-b69a3',
    authDomain: 'shop-local-b69a3.firebaseapp.com',
    storageBucket: 'shop-local-b69a3.firebasestorage.app',
  );

}