// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnkoIrJtqhh6rC5p8dNwraiqMa9ubFqU',
    appId: '1:431763454927:web:87820d8219e46aa5b170ba',
    messagingSenderId: '431763454927',
    projectId: 'shoplocal-299a6',
    authDomain: 'shoplocal-299a6.firebaseapp.com',
    storageBucket: 'shoplocal-299a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtFmnDF62Kc9BWp56X3vb5t8Az9YpnXk',
    appId: '1:431763454927:android:b004719f15f14eceb170ba',
    messagingSenderId: '431763454927',
    projectId: 'shoplocal-299a6',
    storageBucket: 'shoplocal-299a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5gJv-S58NJ5tr2UJHgNGOXrnORLsrTbU',
    appId: '1:431763454927:ios:42d6774355dc3744b170ba',
    messagingSenderId: '431763454927',
    projectId: 'shoplocal-299a6',
    storageBucket: 'shoplocal-299a6.firebasestorage.app',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5gJv-S58NJ5tr2UJHgNGOXrnORLsrTbU',
    appId: '1:431763454927:ios:42d6774355dc3744b170ba',
    messagingSenderId: '431763454927',
    projectId: 'shoplocal-299a6',
    storageBucket: 'shoplocal-299a6.firebasestorage.app',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnkoIrJtqhh6rC5p8dNwraiqMa9ubFqU',
    appId: '1:431763454927:web:11514245064df420b170ba',
    messagingSenderId: '431763454927',
    projectId: 'shoplocal-299a6',
    authDomain: 'shoplocal-299a6.firebaseapp.com',
    storageBucket: 'shoplocal-299a6.firebasestorage.app',
  );
}
