// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgI819r0j8gJmkQPRF3nHydIJuL42eQ4',
    appId: '1:1018530647998:web:25398dc0dfc7353830b3ef',
    messagingSenderId: '1018530647998',
    projectId: 'shoplocal-e4903',
    authDomain: 'shoplocal-e4903.firebaseapp.com',
    storageBucket: 'shoplocal-e4903.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU-946f2sU7aFJdC1Bm2XV4cIq-eG6g2o',
    appId: '1:1018530647998:android:467993a1d6e2d74b30b3ef',
    messagingSenderId: '1018530647998',
    projectId: 'shoplocal-e4903',
    storageBucket: 'shoplocal-e4903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-YAChsg3PA6HkLH6WV1S2CWEU11RQWEs',
    appId: '1:1018530647998:ios:f979f39ef592ac8230b3ef',
    messagingSenderId: '1018530647998',
    projectId: 'shoplocal-e4903',
    storageBucket: 'shoplocal-e4903.firebasestorage.app',
    iosClientId: '1018530647998-hsvia7oksk8vtshtpve2sfs9ujrorjs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-YAChsg3PA6HkLH6WV1S2CWEU11RQWEs',
    appId: '1:1018530647998:ios:f979f39ef592ac8230b3ef',
    messagingSenderId: '1018530647998',
    projectId: 'shoplocal-e4903',
    storageBucket: 'shoplocal-e4903.firebasestorage.app',
    iosClientId: '1018530647998-hsvia7oksk8vtshtpve2sfs9ujrorjs2.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopLocal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqgI819r0j8gJmkQPRF3nHydIJuL42eQ4',
    appId: '1:1018530647998:web:f9e60849130844e530b3ef',
    messagingSenderId: '1018530647998',
    projectId: 'shoplocal-e4903',
    authDomain: 'shoplocal-e4903.firebaseapp.com',
    storageBucket: 'shoplocal-e4903.firebasestorage.app',
  );

}